-- call :Lushify
local lush = require("lush")
---@diagnostic disable
local hsl = lush.hsl
local hsluv = lush.hsluv
local theme = lush(function(injected_functions)
  local sym = injected_functions.sym
  return {
    SpecialKey                                 { fg="#b968fc", },
    TermCursor                                 { gui="reverse", },
    NonText                                    { bg="none", fg="#666666", gui="bold", },
    EndOfBuffer                                { NonText },
    Whitespace                                 { NonText },
    markdownHeadingRule                        { NonText },
    markdownCodeDelimiter                      { NonText },
    Directory                                  { fg="#8edf5f", bg="#000000", },
    gitCommitFile                              { Directory },
    ErrorMsg                                   { bg="#5b2b41", fg="#E1D6F8", },
    NvimInvalidSpacing                         { ErrorMsg },
    IncSearch                                  { fg="#222222", bg="#D99145", },
    FzfLuaSearch                               { IncSearch },
    Search                                     { fg="#222222", bg="#87FF5F", },
    QuickFixLine                               { Search },
    Substitute                                 { Search },
    MoreMsg                                    { fg="#87FF5F", gui="bold", },
    ModeMsg                                    { gui="bold", },
    LineNr                                     { fg="#000000", bg="#67478a", },
    LineNrAbove                                { LineNr },
    LineNrBelow                                { LineNr },
    CursorLineNr                               { fg="#87FF5F", gui="bold", bg="#39274D", },
    FzfLuaCursorLineNr                         { CursorLineNr },
    Question                                   { fg="#87FF5F", gui="bold", },
    StatusLine                                 { fg="#b968fc", gui="bold", bg="#222222", },
    MsgSeparator                               { StatusLine },
    StatusLineNC                               { fg="#666666", gui="bold", bg="#222222", },
    Ignore                                     { fg="#444444", gui="underline", },
    VertSplit                                  { fg="#875FAF", bg="#201430", },
    WinSeparator                               { VertSplit },
    Title                                      { fg="#87FF5F", gui="bold", },
    FloatTitle                                 { Title },
    helpHeadline                               { Title },
    Visual                                     { fg="#222222", bg="#8edf5f", },
    TelescopeSelection                         { Visual },
    WarningMsg                                 { fg="#E6BB85", },
    WildMenu                                   { fg="black", bg="#875faf", },
    Folded                                     { fg="#E6BB85", bg="#000000", },
    FoldColumn                                 { fg="#666666", bg="#483160", },
    CursorLineFold                             { FoldColumn },
		DiffAdded                                  { bg="#000000", fg="#87FF5F", },
		DiffRemoved                                { bg="#000000", fg="#E6BB85", },
		DiffAdd                                    { fg="#222222", bg="#87FF5F", },
    DiffChange                                 { fg="#222222", bg="#D99145", },
    DiffDelete                                 { fg="#000000", gui="bold", bg="#5b2b41", },
    DiffText                                   { fg="#222222", gui="bold", bg="#E6BB85", },
    SignColumn                                 { fg="#666666", bg="#483160" },
    CursorLineSign                             { SignColumn },
    Conceal                                    { Ignore },
    SpellBad                                   { fg="#5b2b41", gui="underline", bg="#000000", },
    SpellCap                                   { fg="#87FF5F", gui="underline", bg="#000000",},
    SpellRare                                  { fg="#E6BB85", gui="underline", bg="#000000",},
    SpellLocal                                 { fg="#D99145", gui="underline", bg="#000000",},
    Pmenu                                      { fg="#b968fc", bg="#483160", },
    PmenuKind                                  { Pmenu },
    PmenuExtra                                 { Pmenu },
    NormalFloat                                { Pmenu },
		FloatBorder                                { bg="#201430", fg="#b968fc", },
    PmenuSel                                   { fg="#222222", bg="#9cda7c", },
    PmenuKindSel                               { PmenuSel },
    PmenuExtraSel                              { PmenuSel },
    PmenuSbar                                  { bg="#666666", },
    FzfLuaScrollFloatEmpty                     { PmenuSbar },
    PmenuThumb                                 { fg="#b968fc", bg="#b968fc", },
    FzfLuaScrollFloatFull                      { PmenuThumb },
    TabLine                                    { fg="#666666", bg="#111111", },
    TabLineSep                                 { fg="#000000", bg="#201430", },
    TabLineSelSep                              { fg="#9cda7c", gui="bold", bg="#201430", },
    TabLineSel                                 { bg="#9cda7c", gui="bold", fg="#201430", },
    TabLineFill                                { fg="#87ff5f", bg="#201430", },
    CursorColumn                               { bg="#39274D", },
    CursorLine                                 { bg="#39274D", },
    FzfLuaCursorLine                           { CursorLine },
    ColorColumn                                { bg="#67478a", },
    WinBar                                     { gui="bold", },
    WinBarNC                                   { WinBar },
    Cursor                                     { fg="#222222", bg="#D99145", },
    FzfLuaCursor                               { Cursor },
    lCursor                                    { fg="bg", bg="fg", },
    Normal                                     { fg="#e1d6f8", bg="#201430", },
    NvimSpacing                                { Normal },
    FzfLuaNormal                               { Normal },
    FzfLuaBorder                               { Normal },
    javaScript                                 { Normal },
    lessVariableValue                          { Normal },
    FloatShadow                                { bg="#101010", },
    FloatShadowThrough                         { bg="#151515", },
    RedrawDebugNormal                          { gui="reverse", },
    RedrawDebugClear                           { bg="#E6BB85", fg="#222222" },
    RedrawDebugComposed                        { bg="#9cda7c", fg="#222222" },
    RedrawDebugRecompose                       { bg="#D99145", fg="#222222" },
    Error                                      { fg="#e1d6f8", bg="#5b2b41", },
    NvimInvalid                                { Error },
    Todo                                       { fg="#b968fc", gui="bold,underline", },
    String                                     { fg="#ab92fc", },
    NvimString                                 { String },
    phpHereDoc                                 { String },
    markdownCodeBlock                          { String },
    NERDTreeExecFile                           { String },
    helpExample                                { String },
    CtrlPMatch                                 { String },
    Constant                                   { fg="#D99145", },
    Character                                  { Constant },
    rubyConstant                               { Constant },
    vimHiAttrib                                { Constant },
    Number                                     { fg="#8edf5f", },
    Float                                      { Number },
    NvimNumber                                 { Number },
    rubyInstanceVariable                       { Number },
    Boolean                                    { fg="#9cda7c", },
    Function                                   { fg="#9cda7c", },
    Identifier                                 { fg="#b968fc", },
    NvimIdentifier                             { Identifier },
    rubyLocalVariableOrMethod                  { Identifier },
    Statement                                  { fg="#87FF5F", gui="bold", },
    Conditional                                { Statement },
    Repeat                                     { Statement },
    Label                                      { Statement },
    Exception                                  { Statement },
    rubyDefine                                 { Statement },
    phpDefine                                  { Statement },
    helpHyperTextEntry                         { Statement },
    Keyword                                    { Statement  },
    PreProc                                    { Keyword },
    Include                                    { PreProc },
    Define                                     { PreProc },
    Macro                                      { PreProc },
    PreCondit                                  { PreProc },
    Type                                       { fg="#9cda7c", gui="bold", },
    StorageClass                               { Type },
    Structure                                  { Type },
    Typedef                                    { Type },
    NvimNumberPrefix                           { Type },
    NvimOptionSigil                            { Type },
    Special                                    { fg="#8BD450", },
    Tag                                        { Special },
    SpecialChar                                { Special },
    SpecialComment                             { Special },
    Debug                                      { Special },
    TelescopeMatching                          { Special },
    TelescopeResultsFileIcon                   { Special },
    Delimiter                                  { fg="#b968fc", },
    Operator                                   { Delimiter },
    NvimParenthesis                            { Delimiter },
    NvimColon                                  { Delimiter },
    NvimComma                                  { Delimiter },
    NvimArrow                                  { Delimiter },
    javaScriptBraces                           { Delimiter },
    markdownLinkDelimiter                      { Delimiter },
    markdownURLDelimiter                       { Delimiter },
    vimSetSep                                  { Delimiter },
    vimContinue                                { Delimiter },
    DiagnosticError                            { fg="#db6088", },
    DiagnosticFloatingError                    { DiagnosticError },
    DiagnosticErrorFloating                    { DiagnosticError },
    DiagnosticWarn                             { fg="#D99145", },
    DiagnosticFloatingWarn                     { DiagnosticWarn },
    DiagnosticInfo                             { fg="#ab92fc", },
    DiagnosticFloatingInfo                     { DiagnosticInfo },
    DiagnosticHint                             { fg="#ab92fc", },
    DiagnosticFloatingHint                     { DiagnosticHint },
    DiagnosticOk                               { fg="#8edf5f", },
    DiagnosticVirtualTextOk                    { DiagnosticOk },
    DiagnosticFloatingOk                       { DiagnosticOk },
    DiagnosticSignOk                           { DiagnosticOk },
		DiagnosticDeprecated                       { gui="strikethrough", sp="#D99145", },
		DiagnosticUnnecessary                      { fg="#666666", gui="underline", },
    DiagnosticUnderlineError                   { gui="underline", },
    DiagnosticUnderlineWarn                    { gui="underline", },
    DiagnosticUnderlineInfo                    { gui="underline", },
    DiagnosticUnderlineHint                    { gui="underline", },
    DiagnosticUnderlineOk                      { gui="underline", },
    DiagnosticVirtualTextError                 { fg="#db6088", bg="#452F5C", },
    DiagnosticVirtualTextWarn                  { fg="#D99145", bg="#452F5C", },
    DiagnosticVirtualTextInfo                  { fg="#8edf5f", bg="#452F5C", },
    DiagnosticVirtualTextHint                  { fg="#8edf5f", bg="#452F5C", },
    DiagnosticSignError                        { fg="#db6088", bg="#452F5C", },
    DiagnosticSignWarn                         { fg="#D99145", bg="#452F5C", },
    DiagnosticSignInfo                         { fg="#ab92fc", bg="#452F5C", },
    DiagnosticSignHint                         { fg="#ab92fc", bg="#452F5C", },
    Comment                                    { bg="#39274D", fg="#a1a0ad", },
    NERDTreeHelp                               { Comment },
    helpSectionDelim                           { Comment },
    CtrlPLinePre                               { Comment },
    LspCodeLens                                { Comment },
    Underlined                                 { fg="#9cda7c", gui="underline", },
    htmlLink                                   { Underlined },
    helpHyperTextJump                          { Underlined },
    helpURL                                    { Underlined },
    MatchParen                                 { fg="#b968fc", gui="bold,underline", },
    NvimInternalError                          { fg="#000000", bg="#5b2b41", },
    NvimFigureBrace                            { NvimInternalError },
    NvimSingleQuotedUnknownEscape              { NvimInternalError },
    NvimInvalidSingleQuotedUnknownEscape       { NvimInternalError },
    LazyReasonRuntime                          { },
    LazyButtonActive                           { bg="#9cda7c", fg="#222222", },
    LazyDimmed                                 { },
    LazyTaskOutput                             { bg="#201430",},
    LazyTaskError                              { NvimInternalError },
    LazyCommitScope                            { bg="#201430", },
    LazyCommitType                             { bg="#201430", },
    LazyCommitIssue                            { bg="#201430", },
    LazyReasonFt                               { bg="#201430", },
    LazyProp                                   { bg="#201430", },
    LazyCommit                                 { },
    LazyUrl                                    { bg="#000000" },
    LazyReasonCmd                              { },
    LazyValue                                  { },
    LazyNormal                                 { bg="#452F5C", },
    LazyNoCond                                 { },
    LazyComment                                { },
    LazyH2                                     { fg="#9cda7c", bg="#201430", },
    LazyReasonSource                           { },
    LazyH1                                     { fg="#9cda7c", bg="#201430", },
    LazyReasonStart                            { },
    LazyLocal                                  { },
    LazyReasonImport                           { },
    LazyDir                                    { },
    LazyReasonKeys                             { },
    LazyProgressDone                           { },
    LazyReasonEvent                            { },
    LazyProgressTodo                           { },
    LazyReasonPlugin                           { },
    LazySpecial                                { Special },
    LazyButton                                 { bg="#201430", },
		MasonNormal                                { LazyNormal },
		MasonHeader                                { bg="#201430", fg="#b968fc"},
		MasonHeaderSecondary                       { LazyButtonActive },
		MasonMuted                                 { bg="#000000", fg="#8edf5f" },
		MasonHighlight                             { bg="#452f5c", fg="#8edf5f"},
		MasonMutedBlock                            { MasonMuted },
		MasonMutedBlockBold                        { MasonHighlight },
		MasonHighlightBlock                        { LazyH2 },
		MasonHighlightBlockBold                    { LazyH1 },
		MasonHighlightBlockSecondary               { },
		MasonHighlightBlockBoldSecondary           { },
		MasonHighlightSecondary                    { },
		MasonError                                 { },
		MasonWarning                               { },
		MasonHeading                               { },
    User1                                      { fg="#87FF5F", bg="#452F5C", },
    User2                                      { fg="#b968fc", bg="#452F5C", },
    User3                                      { fg="#DB6088", bg="#452F5C", },
    User4                                      { fg="#D99145", bg="#452F5C", },
    User5                                      { fg="#ab92fc", bg="#452F5C", },
    User6                                      { fg="#9cda7c", bg="#452F5C", },
    User7                                      { fg="#a4d2ec", bg="#452F5C", },
    User8                                      { fg="#ce67f0", bg="#452F5C", },
    User9                                      { fg="#875FAF", bg="#452F5C", },
    htmlTagName                                { fg="#87FF5F", },
    htmlTag                                    { fg="#87FF5F", },
    htmlEndTag                                 { htmlTag },
    htmlArg                                    { fg="#87FF5F", },
    htmlH1                                     { gui="bold", },
    htmlBold                                   { gui="bold", },
    htmlItalic                                 { gui="underline", },
    htmlUnderline                              { gui="underline", },
    htmlUnderlineItalic                        { gui="underline", },
    htmlBoldItalic                             { gui="bold,underline", },
    htmlBoldUnderline                          { gui="bold,underline", },
    htmlBoldUnderlineItalic                    { gui="bold,underline", },
    xmlTagName                                 { fg="#9cda7c", },
    xmlString                                  { xmlTagName },
    xmlTag                                     { fg="#8edf5f", },
    xmlAttrib                                  { xmlTag },
    xmlEndTag                                  { xmlTag },
    xmlEqual                                   { xmlTag },
    phpSpecialFunction                         { fg="#8BD450", },
    phpIdentifier                              { fg="#E6BB85", },
    phpVarSelector                             { phpIdentifier },
    markdownBold                               { gui="bold", },
    markdownItalic                             { gui="underline", },
    gitCommitBranch                            { fg="#E6BB85", },
    gitCommitSelectedType                      { fg="#87FF5F", },
    gitCommitSelectedFile                      { fg="#87FF5F", },
    gitCommitUnmergedType                      { fg="#D99145", },
    gitCommitDiscardedType                     { gitCommitUnmergedType },
    gitCommitUnmergedFile                      { fg="#D99145", },
    gitCommitUntrackedFile                     { gitCommitUnmergedFile },
    gitCommitDiscardedFile                     { gitCommitUnmergedFile },
    GitSignsAdd                                { fg="#87FF5F", bg="#483160", },
    GitSignsChange                             { fg="#9F50E1", bg="#483160", },
    GitSignsDelete                             { fg="#DB6088", bg="#483160", },
    lessVariable                               { fg="#E6BB85", },
    shDerefSimple                              { fg="#E6BB85", },
    shDerefVar                                 { shDerefSimple },
    mustacheSection                            { gui="bold", },
    mustacheMarker                             { fg="#D99145", },
    mustacheVariable                           { fg="#E6BB85", },
    mustacheVariableUnescape                   { fg="#D99145", },
    mustachePartial                            { fg="#D99145", },
    SyntasticErrorSign                         { fg="#E6BB85", },
    SyntasticWarningSign                       { fg="#D99145", },
    netrwExe                                   { fg="#D99145", },
    netrwClassify                              { fg="#666666", gui="bold", },
    LspBorderBG                                { FloatBorder },
    DiagnosticHintFloating                     { fg="#8edf5f", },
    DiagnosticVirtualTextWarning               { fg="#b968fc", },
    DiagnosticWarning                          { fg="#E6BB85", },
    DiagnosticFloatingWarning                  { DiagnosticWarning },
    DiagnosticWarningFloating                  { fg="#b968fc", },
    LspFloatWinNormal                          { fg="#b968fc", bg="#43492a", },
    LspReferenceRead                           { fg="#87FF5F", gui="bold,undercurl", sp="#D99145", },
    LspReferenceText                           { fg="#b968fc", gui="bold,undercurl", bg="#43492a", sp="#D99145", },
    LspReferenceWrite                          { fg="#87FF5F", gui="bold,undercurl", sp="#D99145", },
    LspSignatureActiveParameter                { gui="bold,underline,italic", sp="#D99145", },
    sym"@attribute"                            { Constant },
    sym"@attribute.builtin"                    { Identifier },
    sym"@boolean"                              { Boolean },
    sym"@character"                            { Character },
    sym"@character.special"                    { SpecialChar },
    sym"@comment"                              { Comment },
    sym"@comment.documentation"                { fg="#ada4a0", },
    sym"@comment.error"                        { ErrorMsg },
    sym"@comment.note"                         { fg="#ab92fc", gui="bold", },
    sym"@comment.todo"                         { Todo },
    sym"@comment.warning"                      { WarningMsg },
    sym"@constant"                             { Constant },
    sym"@constant.builtin"                     { Special },
    sym"@constant.macro"                       { Define },
    sym"@constructor"                          { Special },
    sym"@diff.delta"                           { DiffChange },
    sym"@diff.minus"                           { DiffDelete },
    sym"@diff.plus"                            { DiffAdd },
    sym"@field"                                { Identifier },
    sym"@function"                             { Function },
    sym"@function.builtin"                     { Type },
    sym"@function.call"                        { Function },
    sym"@function.macro"                       { Macro },
    sym"@function.method"                      { Function },
    sym"@function.method.call"                 { Function },
    sym"@keyword"                              { Keyword },
    sym"@keyword.conditional"                  { Conditional },
    sym"@keyword.conditional.ternary"          { Conditional },
    sym"@keyword.coroutine"                    { Keyword },
    sym"@keyword.debug"                        { Debug },
    sym"@keyword.exception"                    { Exception },
    sym"@keyword.function"                     { Keyword },
    sym"@keyword.import"                       { Keyword },
    sym"@keyword.lua"                          { Include },
    sym"@keyword.modifier"                     { Keyword },
    sym"@keyword.modifier.ruby"                { Keyword },
    sym"@keyword.operator"                     { Keyword },
    sym"@keyword.repeat"                       { Repeat },
    sym"@keyword.return"                       { Keyword },
    sym"@keyword.type"                         { Keyword },
    sym"@keyword.vim"                          { Keyword },
    sym"@label"                                { Label },
    sym"@lsp.type.comment"                     { Comment },
    sym"@lsp.type.decorator"                   { Function },
    sym"@lsp.type.enumMember"                  { Constant },
    sym"@lsp.type.function"                    { Function },
    sym"@lsp.type.method"                      { Function },
    sym"@lsp.type.parameter"                   { Identifier },
    sym"@lsp.type.property"                    { fg="#9F50E1", },
    sym"@lsp.type.type"                        { Type },
    sym"@lsp.type.variable"                    { Identifier },
    sym"@markup.checked"                       { Statement },
    sym"@markup.heading"                       { Title },
    sym"@markup.heading.1"                     { Title },
    sym"@markup.heading.2"                     { Title },
    sym"@markup.heading.3"                     { Title },
    sym"@markup.heading.4"                     { Title },
    sym"@markup.heading.5"                     { Title },
    sym"@markup.heading.6"                     { Title },
    sym"@markup.italic"                        { gui="italic", },
    sym"@markup.link"                          { Underlined },
    sym"@markup.link.label"                    { Underlined },
    sym"@markup.link.url"                      { Underlined },
    sym"@markup.list"                          { Statement },
    sym"@markup.math"                          { Identifier },
    sym"@markup.quote"                         { String },
    sym"@markup.strikethrough"                 { gui="strikethrough", },
    sym"@markup.strong"                        { gui="bold" },
    sym"@markup.unchecked"                     { Statement },
    sym"@markup.underline"                     { gui="underline", },
    sym"@method"                               { Function },
    sym"@module"                               { Typedef },
    sym"@module.builtin"                       { Typedef },
    sym"@namespace"                            { Identifier },
    -- sym"@nospell"                              {},
    sym"@number"                               { Number },
    sym"@number.float"                         { Float },
    sym"@operator"                             { Operator },
    sym"@parameter"                            { Identifier },
    sym"@preproc"                              { Keyword },
    sym"@property"                             { fg="#9F50E1",},
    sym"@punctuation"                          { Delimiter },
    sym"@punctuation"                          { Delimiter },
    sym"@punctuation.bracket"                  { Delimiter },
    sym"@punctuation.special"                  { Delimiter },
    -- sym"@spell"                                {},
    sym"@string"                               { String },
    sym"@string.docstrings"                    { Comment },
    sym"@string.escape"                        { Character },
    sym"@string.regexp"                        { Special },
    sym"@string.special"                       { Special },
    sym"@string.special.path"                  { Character },
    sym"@string.special.symbol"                { Identifier },
    sym"@string.special.url"                   { Underlined },
    sym"@tag"                                  { Tag },
    sym"@tag.attribute"                        { Identifier },
    sym"@tag.builtin"                          { Tag },
    sym"@tag.delimiter"                        { Include },
    sym"@text.diff.add"                        { DiffAdd },
    sym"@text.diff.delete"                     { DiffDelete },
    sym"@text.literal"                         { Comment },
    sym"@text.reference"                       { Identifier },
    sym"@text.title"                           { Title },
    sym"@text.todo"                            { Todo },
    sym"@text.underline"                       { Underlined },
    sym"@text.uri"                             { Underlined },
    sym"@type"                                 { Type },
    sym"@type"                                 { Type },
    sym"@type.builtin"                         { Typedef },
    sym"@type.definition"                      { Typedef },
    sym"@variable"                             { Identifier },
    sym"@variable.builtin"                     { Identifier },
    sym"@variable.member"                      { fg="#9F50E1", },
    sym"@variable.parameter"                   { Normal },
    sym"@variable.parameter.builtin"           { Identifier },
    TelescopeSelectionCaret                    { fg="#000000", gui="bold", bg="#8edf5f", },
    TelescopeBorder                            { fg="#67478a", bg="#39274D", },
    TelescopePromptCounter                     { TelescopeBorder },
    TelescopeResultsBorder                     { TelescopeBorder },
    TelescopePreviewBorder                     { TelescopeBorder },
    TelescopeTitle                             { fg="#87FF5F", bg="#39274D", },
    TelescopePromptTitle                       { TelescopeTitle },
    TelescopeNormal                            { bg="#201430", },
    TelescopePreviewNormal                     { bg="#201430", },
    TelescopePromptNormal                      { bg="#39274D", },
    TelescopeResultsNormal                     { bg="#201430", },
    TelescopeResultsTitle                      { TelescopeTitle },
    TelescopePreviewTitle                      { TelescopeTitle },
    TelescopePromptPrefix                      { TelescopeTitle },
    TelescopePromptBorder                      { fg="#67478a", bg="#39274D", },
		TelescopePreviewLine                       { TelescopeSelection },
		CurSearch                                  { Search },
    IblIndent                                  { fg="#39274C", gui="nocombine", },
    IblWhitespace                              { fg="#402C56", gui="nocombine", },
    IblScope                                   { fg="#483160", gui="nocombine", },
    WhichKey                                   { bg="none", fg="#87FF5F" },
    WhichKeyBorder                             { bg="#39274D", },
    WhichKeyDesc                               { fg="#E1D6F8", bg="none",},
    WhichKeyGroup                              { fg="#E1D6F8", bg="#39274D",},
    WhichKeySeparator                          { bg="none", fg="#875FAF", },
    WhichKeyFloat                              { bg="#39274D",},
    WhichKeyValue                              { bg="none", fg="#E6BB85", },
    TelescopeResultsIdentifier                 { Identifier },
    TelescopeResultsLineNr                     { LineNr },
    TelescopeResultsVariable                   { sym"@property" },
    TelescopeResultsStruct                     { Constant },
    TelescopeResultsOperator                   { Operator },
    TelescopeResultsMethod                     { sym"@method" },
    TelescopeResultsFunction                   { Function },
    TelescopeResultsField                      { },
    TelescopeResultsConstant                   { Constant },
    TelescopeResultsClass                      { Special },
    TelescopeResultsDiffUntracked              { },
    TelescopePreviewMessageFillchar            { },
    TelescopePreviewMessage                    { fg="#87FF5F", gui="bold", },
    TelescopePreviewDate                       { },
    TelescopePreviewGroup                      { },
    TelescopePreviewUser                       { },
    TelescopePreviewSize                       { },
    TelescopePreviewSticky                     { },
    TelescopePreviewHyphen                     { },
    TelescopePreviewExecute                    { },
    TelescopePreviewWrite                      { },
    TelescopePreviewRead                       { },
    TelescopePreviewSocket                     { },
    TelescopePreviewLink                       { },
    TelescopePreviewBlock                      { },
    TelescopePreviewDirectory                  { String },
    TelescopePreviewCharDev                    { },
    TelescopePreviewPipe                       { },
    TelescopePreviewMatch                      { Special },
    TelescopeMultiIcon                         { },
    TelescopeMultiSelection                    { },
    TelescopeResultsSpecialComment             { },
    TelescopeResultsComment                    { },
    TelescopeResultsNumber                     { },
    CmpItemAbbrDeprecated                      { fg="#666666", },
    CmpItemAbbrMatch                           { fg="#87ff5f", },
    CmpItemAbbrMatchFuzzy                      { CmpItemAbbrMatch },
    CmpItemKindVariable                        { String },
    CmpItemKindInterface                       { CmpItemKindVariable },
    CmpItemKindText                            { CmpItemKindVariable },
    CmpItemKindFunction                        { fg="#C586C0", },
    CmpItemKindMethod                          { CmpItemKindFunction },
    CmpItemKindKeyword                         { fg="#D4D4D4", },
    CmpItemKindProperty                        { CmpItemKindKeyword },
    CmpItemKindUnit                            { CmpItemKindKeyword },
    TroubleNormal                              { fg="#E1D6F8", bg="none",},
    TroublePos                                 { fg="#E1D6F8", bg="none",},
    TroubleNormalNC                            { fg="#E1D6F8", bg="none",},
    TroublePreview                             { fg="#E1D6F8", bg="none",},
    TroubleIndentWs                            { fg="#E1D6F8", bg="none",},
    TroubleIndentLast                          { fg="#b968fc", bg="none",},
    TroubleIndentMiddle                        { fg="#b968fc", bg="none",},
    TroubleIndentTop                           { fg="#b968fc", bg="none",},
    TroubleIconOperator                        { fg="#b968fc", bg="none",},
    TroubleIndentFoldOpen                      { fg="#b968fc", bg="none",},
    TroubleIndentFoldClosed                    { fg="#b968fc", bg="none",},
    TroubleFsBasename                          { fg="#E1D6F8", bg="none",},
    TroubleFsSource                            { fg="#E1D6F8", bg="none",},
    TroubleFsFilename                          { fg="#E1D6F8", bg="none",},
    TroubleFsCount                             { fg="#E1D6F8", bg="none",},
    TroubleIconNamespace                       { bg="none",},
    TroubleIconFunction                        { bg="none",},
    TroubleIconConstructor                     { bg="none",},
    TroubleIconConstant                        { bg="none",},
    TroubleIconNull                            { bg="none",},
    TroubleIconClass                           { bg="none",},
    TroubleIconNumber                          { bg="none",},
    TroubleIconBoolean                         { bg="none",},
    TroubleIconObject                          { bg="none",},
    TroubleIconArray                           { bg="none",},
  }
end)
---@diagnostic disable
return theme



