-- call :Lushify
local lush = require("lush")
---@diagnostic disable
local hsl = lush.hsl
local hsluv = lush.hsluv
local theme = lush(function(injected_functions)
  local sym = injected_functions.sym
	local lcl = "#D99145"
	local core = "#000000"
	local dispair = "#101010"
	local tokyo3 = "#111111"
	local fear = "#151515"
	local midnight = "#201430"
	local selee = "#222222"
	local casper = "#39274C"
	local balthasar = "#39274D"
	local melchior = "#402C56"
	local gehirn = "#43492A"
	local lost = "#444444"
	local s2engine = "#452F5C"
	local longingus = "#483160"
	local nerv = "#5B2B41"
	local fog = "#666666"
	local mari = "#67478A"
	local unit01 = "#875FAF"
	local kaworu = "#87FF5F"
	local kozo = "#8BD450"
	local terminaldogma = "#8EDF5F"
	local ritsuko = "#9F50E1"
	local kaji = "#9CDA7C"
	local shinji = "#A1A0AD"
	local adam = "#A4D2EC"
	local dummyplug = "#AB92FC"
	local gendo = "#ADA4A0"
	local atfield = "#B968FC"
	local asuska = "#C586C0"
	local lilith = "#CE67F0"
	local misato = "#DB6088"
	local angle = "#D4D4D4"
	local lcl = "#D99145"
	local rei = "#E1D6F8"
	local penpen = "#E6BB85"
	local b = "bold"
	local buc = "bold,undercurl"
	local bu = "bold,underline"
	local bui = "bold,underline,italic"
	local i = "italic"
	local nc = "nocombine"
	local na = "none"
	local rev = "reverse"
	local strike = "strikethrough"
	local u = "underline"

  return {
    SpecialKey                                 { fg=atfield, },
    TermCursor                                 { gui=rev, },
    NonText                                    { bg=na, fg=fog, gui=b, },
    EndOfBuffer                                { NonText },
    Whitespace                                 { NonText },
    markdownHeadingRule                        { NonText },
    markdownCodeDelimiter                      { NonText },
    Directory                                  { fg=terminaldogma, bg=core, },
    gitCommitFile                              { Directory },
    ErrorMsg                                   { bg=nerv, fg=rei, },
    NvimInvalidSpacing                         { ErrorMsg },
    IncSearch                                  { fg=selee, bg=lcl, },
    FzfLuaSearch                               { IncSearch },
    Search                                     { fg=selee, bg=kaworu, },
    QuickFixLine                               { Search },
    Substitute                                 { Search },
    MoreMsg                                    { fg=kaworu, gui=b, },
    ModeMsg                                    { gui=b, },
    LineNr                                     { fg=core, bg=mari, },
    LineNrAbove                                { LineNr },
    LineNrBelow                                { LineNr },
    CursorLineNr                               { fg=kaworu, gui=b, bg=balthasar, },
    FzfLuaCursorLineNr                         { CursorLineNr },
    Question                                   { fg=kaworu, gui=b, },
    StatusLine                                 { fg=atfield, gui=b, bg=selee, },
    MsgSeparator                               { StatusLine },
    StatusLineNC                               { fg=fog, gui=b, bg=selee, },
    Ignore                                     { fg=lost, gui=u, },
    VertSplit                                  { fg=unit01, bg=midnight, },
    WinSeparator                               { VertSplit },
    Title                                      { fg=kaworu, gui=b, },
    FloatTitle                                 { Title },
    helpHeadline                               { Title },
    Visual                                     { fg=selee, bg=terminaldogma, },
    TelescopeSelection                         { Visual },
    WarningMsg                                 { fg=penpen, },
    WildMenu                                   { fg=core, bg=unit01, },
    Folded                                     { fg=penpen, bg=core, },
    FoldColumn                                 { fg=fog, bg=longingus, },
    CursorLineFold                             { FoldColumn },
		DiffAdded                                  { bg=core, fg=kaworu, },
		DiffRemoved                                { bg=core, fg=penpen, },
		DiffAdd                                    { fg=selee, bg=kaworu, },
    DiffChange                                 { fg=selee, bg=lcl, },
    DiffDelete                                 { fg=core, gui=b, bg=nerv, },
    DiffText                                   { fg=selee, gui=b, bg=penpen, },
    SignColumn                                 { fg=fog, bg=longingus },
    CursorLineSign                             { SignColumn },
    Conceal                                    { Ignore },
    SpellBad                                   { fg=nerv, gui=u, bg=core, },
    SpellCap                                   { fg=kaworu, gui=u, bg=core,},
    SpellRare                                  { fg=penpen, gui=u, bg=core,},
    SpellLocal                                 { fg=lcl, gui=u, bg=core,},
    Pmenu                                      { fg=atfield, bg=longingus, },
    PmenuKind                                  { Pmenu },
    PmenuExtra                                 { Pmenu },
    NormalFloat                                { Pmenu },
		FloatBorder                                { bg=midnight, fg=atfield, },
    PmenuSel                                   { fg=selee, bg=kaji, },
    PmenuKindSel                               { PmenuSel },
    PmenuExtraSel                              { PmenuSel },
    PmenuSbar                                  { bg=fog, },
    FzfLuaScrollFloatEmpty                     { PmenuSbar },
    PmenuThumb                                 { fg=atfield, bg=atfield, },
    FzfLuaScrollFloatFull                      { PmenuThumb },
    TabLine                                    { fg=fog, bg=tokyo3, },
    TabLineSep                                 { fg=core, bg=midnight, },
    TabLineSelSep                              { fg=kaji, gui=b, bg=midnight, },
    TabLineSel                                 { bg=kaji, gui=b, fg=midnight, },
    TabLineFill                                { fg=kaworu, bg=midnight, },
    CursorColumn                               { bg=balthasar, },
    CursorLine                                 { bg=balthasar, },
    FzfLuaCursorLine                           { CursorLine },
    ColorColumn                                { bg=mari, },
    WinBar                                     { gui=b, },
    WinBarNC                                   { WinBar },
    Cursor                                     { fg=selee, bg=lcl, },
    FzfLuaCursor                               { Cursor },
    lCursor                                    { fg="bg", bg="fg", },
    Normal                                     { fg=rei, bg=midnight, },
    NvimSpacing                                { Normal },
    FzfLuaNormal                               { Normal },
    FzfLuaBorder                               { Normal },
    javaScript                                 { Normal },
    lessVariableValue                          { Normal },
    FloatShadow                                { bg=dispair, },
    FloatShadowThrough                         { bg=fear, },
    RedrawDebugNormal                          { gui=rev, },
    RedrawDebugClear                           { bg=penpen, fg=selee, },
    RedrawDebugComposed                        { bg=kaji, fg=selee, },
    RedrawDebugRecompose                       { bg=lcl, fg=selee, },
    Error                                      { fg=rei, bg=nerv, },
    NvimInvalid                                { Error },
    Todo                                       { fg=atfield, gui=bu, },
    String                                     { fg=dummyplug, },
    NvimString                                 { String },
    phpHereDoc                                 { String },
    markdownCodeBlock                          { String },
    NERDTreeExecFile                           { String },
    helpExample                                { String },
    CtrlPMatch                                 { String },
    Constant                                   { fg=lcl, },
    Character                                  { Constant },
    rubyConstant                               { Constant },
    vimHiAttrib                                { Constant },
    Number                                     { fg=terminaldogma, },
    Float                                      { Number },
    NvimNumber                                 { Number },
    rubyInstanceVariable                       { Number },
    Boolean                                    { fg=kaji, },
    Function                                   { fg=kaji, },
    Identifier                                 { fg=atfield, },
    NvimIdentifier                             { Identifier },
    rubyLocalVariableOrMethod                  { Identifier },
    Statement                                  { fg=kaworu, gui=b, },
    Conditional                                { Statement },
    Repeat                                     { Statement },
    Label                                      { Statement },
    Exception                                  { Statement },
    rubyDefine                                 { Statement },
    phpDefine                                  { Statement },
    helpHyperTextEntry                         { Statement },
    Keyword                                    { Statement  },
    PreProc                                    { Keyword },
    Include                                    { PreProc },
    Define                                     { PreProc },
    Macro                                      { PreProc },
    PreCondit                                  { PreProc },
    Type                                       { fg=kaji, gui=b, },
    StorageClass                               { Type },
    Structure                                  { Type },
    Typedef                                    { Type },
    NvimNumberPrefix                           { Type },
    NvimOptionSigil                            { Type },
    Special                                    { fg=kozo, },
    Tag                                        { Special },
    SpecialChar                                { Special },
    SpecialComment                             { Special },
    Debug                                      { Special },
    TelescopeMatching                          { Special },
    TelescopeResultsFileIcon                   { Special },
    Delimiter                                  { fg=atfield, },
    Operator                                   { Delimiter },
    NvimParenthesis                            { Delimiter },
    NvimColon                                  { Delimiter },
    NvimComma                                  { Delimiter },
    NvimArrow                                  { Delimiter },
    javaScriptBraces                           { Delimiter },
    markdownLinkDelimiter                      { Delimiter },
    markdownURLDelimiter                       { Delimiter },
    vimSetSep                                  { Delimiter },
    vimContinue                                { Delimiter },
    DiagnosticError                            { bg=misato, },
    DiagnosticFloatingError                    { DiagnosticError },
    DiagnosticErrorFloating                    { DiagnosticError },
    DiagnosticWarn                             { fg=lcl, },
    DiagnosticFloatingWarn                     { DiagnosticWarn },
    DiagnosticInfo                             { fg=dummyplug, },
    DiagnosticFloatingInfo                     { DiagnosticInfo },
    DiagnosticHint                             { fg=dummyplug, },
    DiagnosticFloatingHint                     { DiagnosticHint },
    DiagnosticOk                               { fg=terminaldogma, },
    DiagnosticVirtualTextOk                    { DiagnosticOk },
    DiagnosticFloatingOk                       { DiagnosticOk },
    DiagnosticSignOk                           { DiagnosticOk },
		DiagnosticDeprecated                       { gui=strike, sp=lcl, },
		DiagnosticUnnecessary                      { fg=fog, gui=u, },
    DiagnosticUnderlineError                   { gui=u, },
    DiagnosticUnderlineWarn                    { gui=u, },
    DiagnosticUnderlineInfo                    { gui=u, },
    DiagnosticUnderlineHint                    { gui=u, },
    DiagnosticUnderlineOk                      { gui=u, },
    DiagnosticVirtualTextError                 { bg=misato, bg=s2engine, },
    DiagnosticVirtualTextWarn                  { fg=lcl, bg=s2engine, },
    DiagnosticVirtualTextInfo                  { fg=terminaldogma, bg=s2engine, },
    DiagnosticVirtualTextHint                  { fg=terminaldogma, bg=s2engine, },
    DiagnosticSignError                        { bg=misato, bg=s2engine, },
    DiagnosticSignWarn                         { fg=lcl, bg=s2engine, },
    DiagnosticSignInfo                         { fg=dummyplug, bg=s2engine, },
    DiagnosticSignHint                         { fg=dummyplug, bg=s2engine, },
    Comment                                    { bg=balthasar, fg=shinji, },
    NERDTreeHelp                               { Comment },
    helpSectionDelim                           { Comment },
    CtrlPLinePre                               { Comment },
    LspCodeLens                                { Comment },
    Underlined                                 { fg=kaji, gui=u, },
    htmlLink                                   { Underlined },
    helpHyperTextJump                          { Underlined },
    helpURL                                    { Underlined },
    MatchParen                                 { fg=atfield, gui=bu, },
    NvimInternalError                          { fg=core, bg=nerv, },
    NvimFigureBrace                            { NvimInternalError },
    NvimSingleQuotedUnknownEscape              { NvimInternalError },
    NvimInvalidSingleQuotedUnknownEscape       { NvimInternalError },
    LazyReasonRuntime                          { },
    LazyButtonActive                           { bg=kaji, fg=selee, },
    LazyDimmed                                 { },
    LazyTaskOutput                             { bg=midnight,},
    LazyTaskError                              { NvimInternalError },
    LazyCommitScope                            { bg=midnight, },
    LazyCommitType                             { bg=midnight, },
    LazyCommitIssue                            { bg=midnight, },
    LazyReasonFt                               { bg=midnight, },
    LazyProp                                   { bg=midnight, },
    LazyCommit                                 { },
    LazyUrl                                    { bg=core },
    LazyReasonCmd                              { },
    LazyValue                                  { },
    LazyNormal                                 { bg=s2engine, },
    LazyNoCond                                 { },
    LazyComment                                { },
    LazyH2                                     { fg=kaji, bg=midnight, },
    LazyReasonSource                           { },
    LazyH1                                     { fg=kaji, bg=midnight, },
    LazyReasonStart                            { },
    LazyLocal                                  { },
    LazyReasonImport                           { },
    LazyDir                                    { },
    LazyReasonKeys                             { },
    LazyProgressDone                           { },
    LazyReasonEvent                            { },
    LazyProgressTodo                           { },
    LazyReasonPlugin                           { },
    LazySpecial                                { Special },
    LazyButton                                 { bg=midnight, },
		MasonNormal                                { LazyNormal },
		MasonHeader                                { bg=midnight, fg=atfield},
		MasonHeaderSecondary                       { LazyButtonActive },
		MasonMuted                                 { bg=core, fg=terminaldogma },
		MasonHighlight                             { bg=s2engine, fg=terminaldogma},
		MasonMutedBlock                            { MasonMuted },
		MasonMutedBlockBold                        { MasonHighlight },
		MasonHighlightBlock                        { LazyH2 },
		MasonHighlightBlockBold                    { LazyH1 },
		MasonHighlightBlockSecondary               { },
		MasonHighlightBlockBoldSecondary           { },
		MasonHighlightSecondary                    { },
		MasonError                                 { },
		MasonWarning                               { },
		MasonHeading                               { },
    User1                                      { fg=kaworu, bg=s2engine, },
    User2                                      { fg=atfield, bg=s2engine, },
    User3                                      { bg=misato, bg=s2engine, },
    User4                                      { fg=lcl, bg=s2engine, },
    User5                                      { fg=dummyplug, bg=s2engine, },
    User6                                      { fg=kaji, bg=s2engine, },
    User7                                      { fg=adam, bg=s2engine, },
    User8                                      { fg=lilith, bg=s2engine, },
    User9                                      { fg=unit01, bg=s2engine, },
    htmlTagName                                { fg=kaworu, },
    htmlTag                                    { fg=kaworu, },
    htmlEndTag                                 { htmlTag },
    htmlArg                                    { fg=kaworu, },
    htmlH1                                     { gui=b, },
    htmlBold                                   { gui=b, },
    htmlItalic                                 { gui=u, },
    htmlUnderline                              { gui=u, },
    htmlUnderlineItalic                        { gui=u, },
    htmlBoldItalic                             { gui=bu, },
    htmlBoldUnderline                          { gui=bu, },
    htmlBoldUnderlineItalic                    { gui=bu, },
    xmlTagName                                 { fg=kaji, },
    xmlString                                  { xmlTagName },
    xmlTag                                     { fg=terminaldogma, },
    xmlAttrib                                  { xmlTag },
    xmlEndTag                                  { xmlTag },
    xmlEqual                                   { xmlTag },
    phpSpecialFunction                         { fg=kozo, },
    phpIdentifier                              { fg=penpen, },
    phpVarSelector                             { phpIdentifier },
    markdownBold                               { gui=b, },
    markdownItalic                             { gui=u, },
    gitCommitBranch                            { fg=penpen, },
    gitCommitSelectedType                      { fg=kaworu, },
    gitCommitSelectedFile                      { fg=kaworu, },
    gitCommitUnmergedType                      { fg=lcl, },
    gitCommitDiscardedType                     { gitCommitUnmergedType },
    gitCommitUnmergedFile                      { fg=lcl, },
    gitCommitUntrackedFile                     { gitCommitUnmergedFile },
    gitCommitDiscardedFile                     { gitCommitUnmergedFile },
    GitSignsAdd                                { fg=kaworu, bg=longingus, },
    GitSignsChange                             { fg=ritsuko, bg=longingus, },
    GitSignsDelete                             { bg=misato, bg=longingus, },
    lessVariable                               { fg=penpen, },
    shDerefSimple                              { fg=penpen, },
    shDerefVar                                 { shDerefSimple },
    mustacheSection                            { gui=b, },
    mustacheMarker                             { fg=lcl, },
    mustacheVariable                           { fg=penpen, },
    mustacheVariableUnescape                   { fg=lcl, },
    mustachePartial                            { fg=lcl, },
    SyntasticErrorSign                         { fg=penpen, },
    SyntasticWarningSign                       { fg=lcl, },
    netrwExe                                   { fg=lcl, },
    netrwClassify                              { fg=fog, gui=b, },
    LspBorderBG                                { FloatBorder },
    DiagnosticHintFloating                     { fg=terminaldogma, },
    DiagnosticVirtualTextWarning               { fg=atfield, },
    DiagnosticWarning                          { fg=penpen, },
    DiagnosticFloatingWarning                  { DiagnosticWarning },
    DiagnosticWarningFloating                  { fg=atfield, },
    LspFloatWinNormal                          { fg=atfield, bg=gehirn, },
    LspReferenceRead                           { fg=kaworu, gui=buc, sp=lcl, },
    LspReferenceText                           { fg=atfield, gui=buc, bg=gehirn, sp=lcl, },
    LspReferenceWrite                          { fg=kaworu, gui=buc, sp=lcl, },
    LspSignatureActiveParameter                { gui=bui, sp=lcl, },
    sym"@attribute"                            { Constant },
    sym"@attribute.builtin"                    { Identifier },
    sym"@boolean"                              { Boolean },
    sym"@character"                            { Character },
    sym"@character.special"                    { SpecialChar },
    sym"@comment"                              { Comment },
    sym"@comment.documentation"                { fg=gendo, },
    sym"@comment.error"                        { ErrorMsg },
    sym"@comment.note"                         { fg=dummyplug, gui=b, },
    sym"@comment.todo"                         { Todo },
    sym"@comment.warning"                      { WarningMsg },
    sym"@constant"                             { Constant },
    sym"@constant.builtin"                     { Special },
    sym"@constant.macro"                       { Define },
    sym"@constructor"                          { Special },
    sym"@diff.delta"                           { DiffChange },
    sym"@diff.minus"                           { DiffDelete },
    sym"@diff.plus"                            { DiffAdd },
    sym"@field"                                { Identifier },
    sym"@function"                             { Function },
    sym"@function.builtin"                     { Type },
    sym"@function.call"                        { Function },
    sym"@function.macro"                       { Macro },
    sym"@function.method"                      { Function },
    sym"@function.method.call"                 { Function },
    sym"@keyword"                              { Keyword },
    sym"@keyword.conditional"                  { Conditional },
    sym"@keyword.conditional.ternary"          { Conditional },
    sym"@keyword.coroutine"                    { Keyword },
    sym"@keyword.debug"                        { Debug },
    sym"@keyword.exception"                    { Exception },
    sym"@keyword.function"                     { Keyword },
    sym"@keyword.import"                       { Keyword },
    sym"@keyword.lua"                          { Include },
    sym"@keyword.modifier"                     { Keyword },
    sym"@keyword.modifier.ruby"                { Keyword },
    sym"@keyword.operator"                     { Keyword },
    sym"@keyword.repeat"                       { Repeat },
    sym"@keyword.return"                       { Keyword },
    sym"@keyword.type"                         { Keyword },
    sym"@keyword.vim"                          { Keyword },
    sym"@label"                                { Label },
    sym"@lsp.type.comment"                     { Comment },
    sym"@lsp.type.decorator"                   { Function },
    sym"@lsp.type.enumMember"                  { Constant },
    sym"@lsp.type.function"                    { Function },
    sym"@lsp.type.method"                      { Function },
    sym"@lsp.type.parameter"                   { Identifier },
    sym"@lsp.type.property"                    { fg=ritsuko, },
    sym"@lsp.type.type"                        { Type },
    sym"@lsp.type.variable"                    { Identifier },
    sym"@markup.checked"                       { Statement },
    sym"@markup.heading"                       { Title },
    sym"@markup.heading.1"                     { Title },
    sym"@markup.heading.2"                     { Title },
    sym"@markup.heading.3"                     { Title },
    sym"@markup.heading.4"                     { Title },
    sym"@markup.heading.5"                     { Title },
    sym"@markup.heading.6"                     { Title },
    sym"@markup.italic"                        { gui=i, },
    sym"@markup.link"                          { Underlined },
    sym"@markup.link.label"                    { Underlined },
    sym"@markup.link.url"                      { Underlined },
    sym"@markup.list"                          { Statement },
    sym"@markup.math"                          { Identifier },
    sym"@markup.quote"                         { String },
    sym"@markup.strikethrough"                 { gui=strike, },
    sym"@markup.strong"                        { gui=b },
    sym"@markup.unchecked"                     { Statement },
    sym"@markup.underline"                     { gui=u, },
    sym"@method"                               { Function },
    sym"@module"                               { Typedef },
    sym"@module.builtin"                       { Typedef },
    sym"@namespace"                            { Identifier },
    -- sym"@nospell"                              {},
    sym"@number"                               { Number },
    sym"@number.float"                         { Float },
    sym"@operator"                             { Operator },
    sym"@parameter"                            { Identifier },
    sym"@preproc"                              { Keyword },
    sym"@property"                             { fg=ritsuko,},
    sym"@punctuation"                          { Delimiter },
    sym"@punctuation"                          { Delimiter },
    sym"@punctuation.bracket"                  { Delimiter },
    sym"@punctuation.special"                  { Delimiter },
    -- sym"@spell"                                {},
    sym"@string"                               { String },
    sym"@string.docstrings"                    { Comment },
    sym"@string.escape"                        { Character },
    sym"@string.regexp"                        { Special },
    sym"@string.special"                       { Special },
    sym"@string.special.path"                  { Character },
    sym"@string.special.symbol"                { Identifier },
    sym"@string.special.url"                   { Underlined },
    sym"@tag"                                  { Tag },
    sym"@tag.attribute"                        { Identifier },
    sym"@tag.builtin"                          { Tag },
    sym"@tag.delimiter"                        { Include },
    sym"@text.diff.add"                        { DiffAdd },
    sym"@text.diff.delete"                     { DiffDelete },
    sym"@text.literal"                         { Comment },
    sym"@text.reference"                       { Identifier },
    sym"@text.title"                           { Title },
    sym"@text.todo"                            { Todo },
    sym"@text.underline"                       { Underlined },
    sym"@text.uri"                             { Underlined },
    sym"@type"                                 { Type },
    sym"@type"                                 { Type },
    sym"@type.builtin"                         { Typedef },
    sym"@type.definition"                      { Typedef },
    sym"@variable"                             { Identifier },
    sym"@variable.builtin"                     { Identifier },
    sym"@variable.member"                      { fg=ritsuko, },
    sym"@variable.parameter"                   { Normal },
    sym"@variable.parameter.builtin"           { Identifier },
    TelescopeSelectionCaret                    { fg=core, gui=b, bg=terminaldogma, },
    TelescopeBorder                            { fg=mari, bg=balthasar, },
    TelescopePromptCounter                     { TelescopeBorder },
    TelescopeResultsBorder                     { TelescopeBorder },
    TelescopePreviewBorder                     { TelescopeBorder },
    TelescopeTitle                             { fg=kaworu, bg=balthasar, },
    TelescopePromptTitle                       { TelescopeTitle },
    TelescopeNormal                            { bg=midnight, },
    TelescopePreviewNormal                     { bg=midnight, },
    TelescopePromptNormal                      { bg=balthasar, },
    TelescopeResultsNormal                     { bg=midnight, },
    TelescopeResultsTitle                      { TelescopeTitle },
    TelescopePreviewTitle                      { TelescopeTitle },
    TelescopePromptPrefix                      { TelescopeTitle },
    TelescopePromptBorder                      { fg=mari, bg=balthasar, },
		TelescopePreviewLine                       { TelescopeSelection },
		CurSearch                                  { Search },
    IblIndent                                  { fg=casper, gui=nc, },
    IblWhitespace                              { fg=melchior, gui=nc, },
    IblScope                                   { fg=longingus, gui=nc, },
    WhichKey                                   { bg=na, fg=kaworu },
    WhichKeyBorder                             { bg=balthasar, },
    WhichKeyDesc                               { fg=rei, bg=na,},
    WhichKeyGroup                              { fg=rei, bg=balthasar,},
    WhichKeySeparator                          { bg=na, fg=unit01, },
    WhichKeyFloat                              { bg=balthasar,},
    WhichKeyValue                              { bg=na, fg=penpen, },
    TelescopeResultsIdentifier                 { Identifier },
    TelescopeResultsLineNr                     { LineNr },
    TelescopeResultsVariable                   { sym"@property" },
    TelescopeResultsStruct                     { Constant },
    TelescopeResultsOperator                   { Operator },
    TelescopeResultsMethod                     { sym"@method" },
    TelescopeResultsFunction                   { Function },
    TelescopeResultsField                      { },
    TelescopeResultsConstant                   { Constant },
    TelescopeResultsClass                      { Special },
    TelescopeResultsDiffUntracked              { },
    TelescopePreviewMessageFillchar            { },
    TelescopePreviewMessage                    { fg=kaworu, gui=b, },
    TelescopePreviewDate                       { },
    TelescopePreviewGroup                      { },
    TelescopePreviewUser                       { },
    TelescopePreviewSize                       { },
    TelescopePreviewSticky                     { },
    TelescopePreviewHyphen                     { },
    TelescopePreviewExecute                    { },
    TelescopePreviewWrite                      { },
    TelescopePreviewRead                       { },
    TelescopePreviewSocket                     { },
    TelescopePreviewLink                       { },
    TelescopePreviewBlock                      { },
    TelescopePreviewDirectory                  { String },
    TelescopePreviewCharDev                    { },
    TelescopePreviewPipe                       { },
    TelescopePreviewMatch                      { Special },
    TelescopeMultiIcon                         { },
    TelescopeMultiSelection                    { },
    TelescopeResultsSpecialComment             { },
    TelescopeResultsComment                    { },
    TelescopeResultsNumber                     { },
    CmpItemAbbrDeprecated                      { fg=fog, },
    CmpItemAbbrMatch                           { fg=kaworu, },
    CmpItemAbbrMatchFuzzy                      { CmpItemAbbrMatch },
    CmpItemKindVariable                        { String },
    CmpItemKindInterface                       { CmpItemKindVariable },
    CmpItemKindText                            { CmpItemKindVariable },
    CmpItemKindFunction                        { fg=asuska, },
    CmpItemKindMethod                          { CmpItemKindFunction },
    CmpItemKindKeyword                         { bg=angle, },
    CmpItemKindProperty                        { CmpItemKindKeyword },
    CmpItemKindUnit                            { CmpItemKindKeyword },
    TroubleNormal                              { fg=rei, bg=na,},
    TroublePos                                 { fg=rei, bg=na,},
    TroubleNormalNC                            { fg=rei, bg=na,},
    TroublePreview                             { fg=rei, bg=na,},
    TroubleIndentWs                            { fg=rei, bg=na,},
    TroubleIndentLast                          { fg=atfield, bg=na,},
    TroubleIndentMiddle                        { fg=atfield, bg=na,},
    TroubleIndentTop                           { fg=atfield, bg=na,},
    TroubleIconOperator                        { fg=atfield, bg=na,},
    TroubleIndentFoldOpen                      { fg=atfield, bg=na,},
    TroubleIndentFoldClosed                    { fg=atfield, bg=na,},
    TroubleFsBasename                          { fg=rei, bg=na,},
    TroubleFsSource                            { fg=rei, bg=na,},
    TroubleFsFilename                          { fg=rei, bg=na,},
    TroubleFsCount                             { fg=rei, bg=na,},
    TroubleIconNamespace                       { bg=na,},
    TroubleIconFunction                        { bg=na,},
    TroubleIconConstructor                     { bg=na,},
    TroubleIconConstant                        { bg=na,},
    TroubleIconNull                            { bg=na,},
    TroubleIconClass                           { bg=na,},
    TroubleIconNumber                          { bg=na,},
    TroubleIconBoolean                         { bg=na,},
    TroubleIconObject                          { bg=na,},
    TroubleIconArray                           { bg=na,},
  }
end)
---@diagnostic disable
return theme



