-- call :Lushify
local nge = require("evangelion.unit01").get()
---@diagnostic disable
local lush = require("lush")
local theme = lush(function(injected_functions)
  local sym = injected_functions.sym
  return {
    SpecialKey                                 { fg = nge.atfield, },
    TermCursor                                 { gui = nge.rev, },
    NonText                                    { bg = nge.na, fg = nge.fog, gui = nge.b, },
    EndOfBuffer                                { NonText },
    Whitespace                                 { NonText },
    markdownHeadingRule                        { NonText },
    markdownCodeDelimiter                      { NonText },
    Directory                                  { fg = nge.terminaldogma, bg = nge.core, },
    gitCommitFile                              { Directory },
    ErrorMsg                                   { bg = nge.nerv, fg = nge.misato, },
    NvimInvalidSpacing                         { ErrorMsg },
    IncSearch                                  { fg = nge.selee, bg = nge.lcl, },
    FzfLuaSearch                               { IncSearch },
    Search                                     { fg = nge.selee, bg = nge.kaworu, },
    QuickFixLine                               { Search },
    Substitute                                 { Search },
    MoreMsg                                    { fg = nge.kaworu, gui = nge.b, },
    ModeMsg                                    { gui = nge.b, },
    LineNr                                     { fg = nge.core, bg = nge.mari, },
    LineNrAbove                                { LineNr },
    LineNrBelow                                { LineNr },
    CursorLineNr                               { fg = nge.kaworu, gui = nge.b, bg = nge.balthasar, },
    FzfLuaCursorLineNr                         { CursorLineNr },
    Question                                   { fg = nge.kaworu, gui = nge.b, },
    StatusLine                                 { fg = nge.atfield, gui = nge.b, bg = nge.selee, },
    MsgSeparator                               { StatusLine },
    StatusLineNC                               { fg = nge.fog, gui = nge.b, bg = nge.selee, },
    Ignore                                     { fg = nge.lost, gui = nge.u, },
    VertSplit                                  { fg = nge.unit01, bg = nge.midnight, },
    WinSeparator                               { VertSplit },
    Title                                      { fg = nge.kaworu, gui = nge.b, },
    FloatTitle                                 { Title },
    helpHeadline                               { Title },
    Visual                                     { fg = nge.selee, bg = nge.terminaldogma, },
    TelescopeSelection                         { bg = nge.balthasar },
    WarningMsg                                 { fg = nge.penpen, },
    WildMenu                                   { fg = nge.core, bg = nge.unit01, },
    Folded                                     { fg = nge.penpen, bg = nge.core, },
    FoldColumn                                 { fg = nge.fog, bg = nge.longingus, },
    CursorLineFold                             { FoldColumn },
		DiffAdded                                  { bg = nge.core, fg = nge.kaworu, },
		DiffRemoved                                { bg = nge.core, fg = nge.penpen, },
		DiffAdd                                    { fg = nge.selee, bg = nge.kaworu, },
    DiffChange                                 { fg = nge.selee, bg = nge.lcl, },
    DiffDelete                                 { fg = nge.misato, gui = nge.b, bg = nge.nerv, },
    DiffText                                   { fg = nge.selee, gui = nge.b, bg = nge.penpen, },
    SignColumn                                 { fg = nge.fog, bg = nge.longingus },
    CursorLineSign                             { SignColumn },
    Conceal                                    { Ignore },
    SpellBad                                   { fg = nge.nerv, gui = nge.bu, bg = nge.misato, },
    SpellCap                                   { fg = nge.kaworu, gui = nge.u, bg = nge.core,},
    SpellRare                                  { fg = nge.penpen, gui = nge.u, bg = nge.core,},
    SpellLocal                                 { fg = nge.lcl, gui = nge.u, bg = nge.core,},
    Pmenu                                      { fg = nge.kaworu, bg = nge.melchior, },
    PmenuKind                                  { fg = nge.mari},
    PmenuExtra                                 { Pmenu },
    NormalFloat                                { Pmenu },
		FloatBorder                                { bg = nge.midnight, fg = nge.atfield, },
    PmenuSel                                   { fg = nge.selee, bg = nge.kaji, },
    PmenuKindSel                               { PmenuSel },
    PmenuExtraSel                              { PmenuSel },
    PmenuSbar                                  { bg = nge.fog, },
    FzfLuaScrollFloatEmpty                     { PmenuSbar },
    PmenuThumb                                 { fg = nge.atfield, bg = nge.atfield, },
    FzfLuaScrollFloatFull                      { PmenuThumb },
    TabLine                                    { fg = nge.fog, bg = nge.tokyo3, },
    TabLineSep                                 { fg = nge.core, bg = nge.midnight, },
    TabLineSelSep                              { fg = nge.kaji, gui = nge.b, bg = nge.midnight, },
    TabLineSel                                 { bg = nge.kaji, gui = nge.b, fg = nge.midnight, },
    TabLineFill                                { fg = nge.kaworu, bg = nge.midnight, },
    CursorColumn                               { bg = nge.balthasar, },
    CursorLine                                 { bg = nge.balthasar, },
    FzfLuaCursorLine                           { CursorLine },
    ColorColumn                                { bg = nge.mari, },
    WinBar                                     { gui = nge.b, },
    WinBarNC                                   { WinBar },
    Cursor                                     { fg = nge.selee, bg = nge.lcl, },
    FzfLuaCursor                               { Cursor },
    lCursor                                    { gui = nge.rev, },
    Normal                                     { fg = nge.rei, bg = nge.midnight, },
    NvimSpacing                                { Normal },
    FzfLuaNormal                               { Normal },
    FzfLuaBorder                               { Normal },
    javaScript                                 { Normal },
    lessVariableValue                          { Normal },
    FloatShadow                                { bg = nge.dispair, },
    FloatShadowThrough                         { bg = nge.fear, },
    RedrawDebugNormal                          { gui = nge.rev, },
    RedrawDebugClear                           { bg = nge.penpen, fg = nge.selee, },
    RedrawDebugComposed                        { bg = nge.kaji, fg = nge.selee, },
    RedrawDebugRecompose                       { bg = nge.lcl, fg = nge.selee, },
    Error                                      { ErrorMsg, },
    NvimInvalid                                { ErrorMsg, },
    Todo                                       { fg = nge.atfield, gui = nge.bu, },
    String                                     { fg = nge.dummyplug, },
    NvimString                                 { String },
    phpHereDoc                                 { String },
    markdownCodeBlock                          { String },
    NERDTreeExecFile                           { String },
    helpExample                                { String },
    CtrlPMatch                                 { String },
    Constant                                   { fg = nge.lcl, },
    Character                                  { Constant },
    rubyConstant                               { Constant },
    vimHiAttrib                                { Constant },
    Number                                     { fg = nge.terminaldogma, },
    Float                                      { Number },
    NvimNumber                                 { Number },
    rubyInstanceVariable                       { Number },
    Boolean                                    { fg = nge.kaji, },
    Function                                   { fg = nge.kaji, },
    Identifier                                 { fg = nge.atfield, },
    NvimIdentifier                             { Identifier },
    rubyLocalVariableOrMethod                  { Identifier },
    Statement                                  { fg = nge.kaworu, gui = nge.b, },
    Conditional                                { Statement },
    Repeat                                     { Statement },
    Label                                      { Statement },
    Exception                                  { Statement },
    rubyDefine                                 { Statement },
    phpDefine                                  { Statement },
    helpHyperTextEntry                         { Statement },
    Keyword                                    { Statement  },
    PreProc                                    { Keyword },
    Include                                    { PreProc },
    Define                                     { PreProc },
    Macro                                      { PreProc },
    PreCondit                                  { PreProc },
    Type                                       { fg = nge.kaji, gui = nge.b, },
    StorageClass                               { Type },
    Structure                                  { Type },
    Typedef                                    { Type },
    NvimNumberPrefix                           { Type },
    NvimOptionSigil                            { Type },
    Special                                    { fg = nge.kozo, },
    Tag                                        { Special },
    SpecialChar                                { Special },
    SpecialComment                             { Special },
    Debug                                      { Special },
    TelescopeMatching                          { Special },
    TelescopeResultsFileIcon                   { Special },
    Delimiter                                  { fg = nge.atfield, },
    Operator                                   { Delimiter },
    NvimParenthesis                            { Delimiter },
    NvimColon                                  { Delimiter },
    NvimComma                                  { Delimiter },
    NvimArrow                                  { Delimiter },
    javaScriptBraces                           { Delimiter },
    markdownLinkDelimiter                      { Delimiter },
    markdownURLDelimiter                       { Delimiter },
    vimSetSep                                  { Delimiter },
    vimContinue                                { Delimiter },
    DiagnosticError                            { ErrorMsg },
    DiagnosticFloatingError                    { ErrorMsg },
    DiagnosticErrorFloating                    { ErrorMsg },
    DiagnosticWarn                             { fg = nge.lcl, },
    DiagnosticFloatingWarn                     { DiagnosticWarn },
    DiagnosticInfo                             { fg = nge.dummyplug, },
    DiagnosticFloatingInfo                     { DiagnosticInfo },
    DiagnosticHint                             { fg = nge.dummyplug, },
    DiagnosticFloatingHint                     { DiagnosticHint },
    DiagnosticOk                               { fg = nge.terminaldogma, },
    DiagnosticVirtualTextOk                    { DiagnosticOk },
    DiagnosticFloatingOk                       { DiagnosticOk },
    DiagnosticSignOk                           { DiagnosticOk },
		DiagnosticDeprecated                       { gui = nge.strike, sp = nge.lcl, },
		DiagnosticUnnecessary                      { fg = nge.fog, gui = nge.u, },
    DiagnosticUnderlineError                   { gui = nge.u, },
    DiagnosticUnderlineWarn                    { gui = nge.u, },
    DiagnosticUnderlineInfo                    { gui = nge.u, },
    DiagnosticUnderlineHint                    { gui = nge.u, },
    DiagnosticUnderlineOk                      { gui = nge.u, },
    DiagnosticVirtualTextError                 { fg = nge.misato, bg = nge.s2engine, },
    DiagnosticVirtualTextWarn                  { fg = nge.lcl, bg = nge.s2engine, },
    DiagnosticVirtualTextInfo                  { fg = nge.terminaldogma, bg = nge.s2engine, },
    DiagnosticVirtualTextHint                  { fg = nge.terminaldogma, bg = nge.s2engine, },
    DiagnosticSignError                        { fg = nge.misato, bg = nge.s2engine, },
    DiagnosticSignWarn                         { fg = nge.lcl, bg = nge.s2engine, },
    DiagnosticSignInfo                         { fg = nge.dummyplug, bg = nge.s2engine, },
    DiagnosticSignHint                         { fg = nge.dummyplug, bg = nge.s2engine, },
    Comment                                    { bg = nge.balthasar, fg = nge.shinji, },
    NERDTreeHelp                               { bg = nge.balthasar, fg = nge.lcl, },
    helpSectionDelim                           { Comment },
    CtrlPLinePre                               { Comment },
    LspCodeLens                                { Comment },
    Underlined                                 { fg = nge.kaji, gui = nge.u, },
    htmlLink                                   { Underlined },
    helpHyperTextJump                          { Underlined },
    helpURL                                    { Underlined },
    MatchParen                                 { fg = nge.atfield, gui = nge.bu, },
    NvimInternalError                          { ErrorMsg },
    NvimFigureBrace                            { ErrorMsg },
    NvimSingleQuotedUnknownEscape              { ErrorMsg },
    NvimInvalidSingleQuotedUnknownEscape       { ErrorMsg },
    LazyReasonRuntime                          { ErrorMsg },
    LazyButtonActive                           { bg = nge.kaji, fg = nge.selee, },
    LazyDimmed                                 { },
    LazyTaskOutput                             { bg = nge.midnight,},
    LazyTaskError                              { ErrorMsg },
    LazyCommitScope                            { bg = nge.midnight, },
    LazyCommitType                             { bg = nge.midnight, },
    LazyCommitIssue                            { bg = nge.midnight, },
    LazyReasonFt                               { bg = nge.midnight, },
    LazyProp                                   { bg = nge.midnight, },
    LazyCommit                                 { },
    LazyUrl                                    { bg = nge.core },
    LazyReasonCmd                              { },
    LazyValue                                  { },
    LazyNormal                                 { bg = nge.s2engine, },
    LazyNoCond                                 { },
    LazyComment                                { },
    LazyH2                                     { fg = nge.kaji, bg = nge.midnight, },
    LazyReasonSource                           { },
    LazyH1                                     { fg = nge.kaji, bg = nge.midnight, },
    LazyReasonStart                            { },
    LazyLocal                                  { },
    LazyReasonImport                           { },
    LazyDir                                    { },
    LazyReasonKeys                             { },
    LazyProgressDone                           { },
    LazyReasonEvent                            { },
    LazyProgressTodo                           { },
    LazyReasonPlugin                           { },
    LazySpecial                                { Special },
    LazyButton                                 { bg = nge.midnight, },
		MasonNormal                                { LazyNormal },
		MasonHeader                                { bg = nge.midnight, fg = nge.atfield},
		MasonHeaderSecondary                       { LazyButtonActive },
		MasonMuted                                 { bg = nge.core, fg = nge.terminaldogma },
		MasonHighlight                             { bg = nge.s2engine, fg = nge.terminaldogma},
		MasonMutedBlock                            { MasonMuted },
		MasonMutedBlockBold                        { MasonHighlight },
		MasonHighlightBlock                        { LazyH2 },
		MasonHighlightBlockBold                    { LazyH1 },
		MasonHighlightBlockSecondary               { },
		MasonHighlightBlockBoldSecondary           { },
		MasonHighlightSecondary                    { },
		MasonError                                 { },
		MasonWarning                               { },
		MasonHeading                               { },
    User1                                      { fg = nge.kaworu, bg = nge.s2engine, },
    User2                                      { fg = nge.atfield, bg = nge.s2engine, },
    User3                                      { fg = nge.misato, bg = nge.s2engine, },
    User4                                      { fg = nge.lcl, bg = nge.s2engine, },
    User5                                      { fg = nge.dummyplug, bg = nge.s2engine, },
    User6                                      { fg = nge.kaji, bg = nge.s2engine, },
    User7                                      { fg = nge.adam, bg = nge.s2engine, },
    User8                                      { fg = nge.lilith, bg = nge.s2engine, },
    User9                                      { fg = nge.unit01, bg = nge.s2engine, },
    htmlTagName                                { fg = nge.kaworu, },
    htmlTag                                    { fg = nge.kaworu, },
    htmlEndTag                                 { htmlTag },
    htmlArg                                    { fg = nge.kaworu, },
    htmlH1                                     { gui = nge.b, },
    htmlBold                                   { gui = nge.b, },
    htmlItalic                                 { gui = nge.u, },
    htmlUnderline                              { gui = nge.u, },
    htmlUnderlineItalic                        { gui = nge.u, },
    htmlBoldItalic                             { gui = nge.bu, },
    htmlBoldUnderline                          { gui = nge.bu, },
    htmlBoldUnderlineItalic                    { gui = nge.bu, },
    xmlTagName                                 { fg = nge.kaji, },
    xmlString                                  { xmlTagName },
    xmlTag                                     { fg = nge.terminaldogma, },
    xmlAttrib                                  { xmlTag },
    xmlEndTag                                  { xmlTag },
    xmlEqual                                   { xmlTag },
    phpSpecialFunction                         { fg = nge.kozo, },
    phpIdentifier                              { fg = nge.penpen, },
    phpVarSelector                             { phpIdentifier },
    markdownBold                               { gui = nge.b, },
    markdownItalic                             { gui = nge.u, },
    gitCommitBranch                            { fg = nge.penpen, },
    gitCommitSelectedType                      { fg = nge.kaworu, },
    gitCommitSelectedFile                      { fg = nge.kaworu, },
    gitCommitUnmergedType                      { fg = nge.lcl, },
    gitCommitDiscardedType                     { gitCommitUnmergedType },
    gitCommitUnmergedFile                      { fg = nge.lcl, },
    gitCommitUntrackedFile                     { gitCommitUnmergedFile },
    gitCommitDiscardedFile                     { gitCommitUnmergedFile },
    GitSignsAdd                                { fg = nge.kaworu, bg = nge.longingus, },
    GitSignsChange                             { fg = nge.ritsuko, bg = nge.longingus, },
    GitSignsDelete                             { fg = nge.misato, bg = nge.longingus, },
    lessVariable                               { fg = nge.penpen, },
    shDerefSimple                              { fg = nge.penpen, },
    shDerefVar                                 { shDerefSimple },
    mustacheSection                            { gui = nge.b, },
    mustacheMarker                             { fg = nge.lcl, },
    mustacheVariable                           { fg = nge.penpen, },
    mustacheVariableUnescape                   { fg = nge.lcl, },
    mustachePartial                            { fg = nge.lcl, },
    SyntasticErrorSign                         { fg = nge.penpen, },
    SyntasticWarningSign                       { fg = nge.lcl, },
    netrwExe                                   { fg = nge.lcl, },
    netrwClassify                              { fg = nge.fog, gui = nge.b, },
    LspBorderBG                                { FloatBorder },
    DiagnosticHintFloating                     { fg = nge.terminaldogma, },
    DiagnosticVirtualTextWarning               { fg = nge.atfield, },
    DiagnosticWarning                          { fg = nge.penpen, },
    DiagnosticFloatingWarning                  { DiagnosticWarning },
    DiagnosticWarningFloating                  { fg = nge.atfield, },
    LspFloatWinNormal                          { fg = nge.atfield, bg = nge.gehirn, },
    LspReferenceRead                           { fg = nge.kaworu, gui = nge.buc, sp = nge.lcl, },
    LspReferenceText                           { fg = nge.atfield, gui = nge.buc, bg = nge.gehirn, sp = nge.lcl, },
    LspReferenceWrite                          { fg = nge.kaworu, gui = nge.buc, sp = nge.lcl, },
    LspSignatureActiveParameter                { gui = nge.bui, sp = nge.lcl, },
    sym"@attribute"                            { Constant },
    sym"@attribute.builtin"                    { Identifier },
    sym"@boolean"                              { Boolean },
    sym"@character"                            { Character },
    sym"@character.special"                    { SpecialChar },
    sym"@comment"                              { Comment },
    sym"@comment.documentation"                { fg = nge.gendo, },
    sym"@comment.error"                        { ErrorMsg },
    sym"@comment.note"                         { fg = nge.dummyplug, gui = nge.b, },
    sym"@comment.todo"                         { Todo },
    sym"@comment.warning"                      { WarningMsg },
    sym"@constant"                             { Constant },
    sym"@constant.builtin"                     { Special },
    sym"@constant.macro"                       { Define },
    sym"@constructor"                          { Special },
    sym"@diff.delta"                           { DiffChange },
    sym"@diff.minus"                           { DiffDelete },
    sym"@diff.plus"                            { DiffAdd },
    sym"@field"                                { Identifier },
    sym"@function"                             { Function },
    sym"@function.builtin"                     { Type },
    sym"@function.call"                        { Function },
    sym"@function.macro"                       { Macro },
    sym"@function.method"                      { Function },
    sym"@function.method.call"                 { Function },
    sym"@keyword"                              { Keyword },
    sym"@keyword.conditional"                  { Conditional },
    sym"@keyword.conditional.ternary"          { Conditional },
    sym"@keyword.coroutine"                    { Keyword },
    sym"@keyword.debug"                        { Debug },
    sym"@keyword.exception"                    { Exception },
    sym"@keyword.function"                     { Keyword },
    sym"@keyword.import"                       { Keyword },
    sym"@keyword.lua"                          { Include },
    sym"@keyword.modifier"                     { Keyword },
    sym"@keyword.modifier.ruby"                { Keyword },
    sym"@keyword.operator"                     { Keyword },
    sym"@keyword.repeat"                       { Repeat },
    sym"@keyword.return"                       { Keyword },
    sym"@keyword.type"                         { Keyword },
    sym"@keyword.vim"                          { Keyword },
    sym"@label"                                { Label },
    sym"@lsp.type.comment"                     { Comment },
    sym"@lsp.type.decorator"                   { Function },
    sym"@lsp.type.enumMember"                  { Constant },
    sym"@lsp.type.function"                    { Function },
    sym"@lsp.type.method"                      { Function },
    sym"@lsp.type.parameter"                   { Identifier },
    sym"@lsp.type.property"                    { fg = nge.ritsuko, },
    sym"@lsp.type.type"                        { Type },
    sym"@lsp.type.variable"                    { Identifier },
    sym"@markup.checked"                       { Statement },
    sym"@markup.heading"                       { Title },
    sym"@markup.heading.1"                     { Title },
    sym"@markup.heading.2"                     { Title },
    sym"@markup.heading.3"                     { Title },
    sym"@markup.heading.4"                     { Title },
    sym"@markup.heading.5"                     { Title },
    sym"@markup.heading.6"                     { Title },
    sym"@markup.italic"                        { gui = nge.i, },
    sym"@markup.link"                          { Underlined },
    sym"@markup.link.label"                    { Underlined },
    sym"@markup.link.url"                      { Underlined },
    sym"@markup.list"                          { Statement },
    sym"@markup.math"                          { Identifier },
    sym"@markup.quote"                         { String },
    sym"@markup.strikethrough"                 { gui = nge.strike, },
    sym"@markup.strong"                        { gui = nge.b },
    sym"@markup.unchecked"                     { Statement },
    sym"@markup.underline"                     { gui = nge.u, },
    sym"@method"                               { Function },
    sym"@module"                               { Typedef },
    sym"@module.builtin"                       { Typedef },
    sym"@namespace"                            { Identifier },
    -- sym"@nospell"                              {},
    sym"@number"                               { Number },
    sym"@number.float"                         { Float },
    sym"@operator"                             { Operator },
    sym"@parameter"                            { Identifier },
    sym"@preproc"                              { Keyword },
    sym"@property"                             { fg = nge.ritsuko,},
    sym"@punctuation"                          { Delimiter },
    sym"@punctuation"                          { Delimiter },
    sym"@punctuation.bracket"                  { Delimiter },
    sym"@punctuation.special"                  { Delimiter },
    -- sym"@spell"                                {},
    sym"@string"                               { String },
    sym"@string.docstrings"                    { Comment },
    sym"@string.escape"                        { Character },
    sym"@string.regexp"                        { Special },
    sym"@string.special"                       { Special },
    sym"@string.special.path"                  { Character },
    sym"@string.special.symbol"                { Identifier },
    sym"@string.special.url"                   { Underlined },
    sym"@tag"                                  { Tag },
    sym"@tag.attribute"                        { Identifier },
    sym"@tag.builtin"                          { Tag },
    sym"@tag.delimiter"                        { Include },
    sym"@text.diff.add"                        { DiffAdd },
    sym"@text.diff.delete"                     { DiffDelete },
    sym"@text.literal"                         { Comment },
    sym"@text.reference"                       { Identifier },
    sym"@text.title"                           { Title },
    sym"@text.todo"                            { Todo },
    sym"@text.underline"                       { Underlined },
    sym"@text.uri"                             { Underlined },
    sym"@type"                                 { Type },
    sym"@type"                                 { Type },
    sym"@type.builtin"                         { Typedef },
    sym"@type.definition"                      { Typedef },
    sym"@variable"                             { Identifier },
    sym"@variable.builtin"                     { Identifier },
    sym"@variable.member"                      { fg = nge.ritsuko, },
    sym"@variable.parameter"                   { Normal },
    sym"@variable.parameter.builtin"           { Identifier },
    TelescopeSelectionCaret                    { fg = nge.kaworu, gui = nge.b, bg = nge.balthasar, },
    TelescopeBorder                            { fg = nge.mari, bg = nge.balthasar, },
    TelescopePromptCounter                     { TelescopeBorder },
    TelescopeResultsBorder                     { TelescopeBorder },
    TelescopePreviewBorder                     { TelescopeBorder },
    TelescopeTitle                             { fg = nge.kaworu, bg = nge.balthasar, },
    TelescopePromptTitle                       { TelescopeTitle },
    TelescopeNormal                            { bg = nge.midnight, },
    TelescopePreviewNormal                     { bg = nge.midnight, },
    TelescopePromptNormal                      { bg = nge.balthasar, },
    TelescopeResultsNormal                     { bg = nge.midnight, },
    TelescopeResultsTitle                      { TelescopeTitle },
    TelescopePreviewTitle                      { TelescopeTitle },
    TelescopePromptPrefix                      { TelescopeTitle },
    TelescopePromptBorder                      { fg = nge.mari, bg = nge.balthasar, },
		TelescopePreviewLine                       { TelescopeSelection },
		CurSearch                                  { Search },
    IblIndent                                  { fg = nge.casper, gui = nge.nc, },
    IblWhitespace                              { fg = nge.melchior, gui = nge.nc, },
    IblScope                                   { fg = nge.longingus, gui = nge.nc, },
    WhichKey                                   { bg = nge.na, fg = nge.kaworu },
    WhichKeyBorder                             { bg = nge.balthasar, },
    WhichKeyDesc                               { fg = nge.rei, bg = nge.na,},
    WhichKeyGroup                              { fg = nge.rei, bg = nge.balthasar,},
    WhichKeySeparator                          { bg = nge.na, fg = nge.unit01, },
    WhichKeyFloat                              { bg = nge.balthasar,},
    WhichKeyValue                              { bg = nge.na, fg = nge.penpen, },
    TelescopeResultsIdentifier                 { Identifier },
    TelescopeResultsLineNr                     { LineNr },
    TelescopeResultsVariable                   { sym"@property" },
    TelescopeResultsStruct                     { Constant },
    TelescopeResultsOperator                   { Operator },
    TelescopeResultsMethod                     { sym"@method" },
    TelescopeResultsFunction                   { Function },
    TelescopeResultsField                      { },
    TelescopeResultsConstant                   { Constant },
    TelescopeResultsClass                      { Special },
    TelescopeResultsDiffUntracked              { },
    TelescopePreviewMessageFillchar            { },
    TelescopePreviewMessage                    { fg = nge.kaworu, gui = nge.b, },
    TelescopePreviewDate                       { },
    TelescopePreviewGroup                      { },
    TelescopePreviewUser                       { },
    TelescopePreviewSize                       { },
    TelescopePreviewSticky                     { },
    TelescopePreviewHyphen                     { },
    TelescopePreviewExecute                    { },
    TelescopePreviewWrite                      { },
    TelescopePreviewRead                       { },
    TelescopePreviewSocket                     { },
    TelescopePreviewLink                       { },
    TelescopePreviewBlock                      { },
    TelescopePreviewDirectory                  { String },
    TelescopePreviewCharDev                    { },
    TelescopePreviewPipe                       { },
    TelescopePreviewMatch                      { Special },
    TelescopeMultiIcon                         { },
    TelescopeMultiSelection                    { },
    TelescopeResultsSpecialComment             { },
    TelescopeResultsComment                    { },
    TelescopeResultsNumber                     { },
    CmpItemAbbrDeprecated                      { fg = nge.fog, },
    CmpItemAbbrMatch                           { fg = nge.kaworu, },
    CmpItemAbbrMatchFuzzy                      { CmpItemAbbrMatch },
    CmpItemKindVariable                        { bg = nge.s2engine, fg = nge.adam, },
    CmpItemKindInterface                       { CmpItemKindVariable },
    CmpItemKindText                            { bg = nge.s2engine, fg = nge.adam, },
    CmpItemKindFunction                        { bg = nge.s2engine, fg = nge.kaworu, },
    CmpItemKindMethod                          { CmpItemKindFunction },
    CmpItemKindKeyword                         { fg = nge.kaworu },
    CmpItemKindProperty                        { CmpItemKindKeyword },
    CmpItemKindUnit                            { CmpItemKindKeyword },
		BlinkCmpMenu                               { fg = nge.terminaldogma, bg = nge.melchior,  },
		BlinkCmpMenuBorder                         { Pmenu },
		BlinkCmpMenuSelection                      { PmenuSel },
		BlinkCmpScrollBarThumb                     { PmenuThumb },
		BlinkCmpScrollBarGutter                    { PmenuSbar },
		BlinkCmpLabel                              { fg = nge.dummyplug},
		BlinkCmpLabelDeprecated                    { NonText },
		BlinkCmpLabelMatch                         { fg = nge.penpen },
		BlinkCmpLabelDetail                        { PmenuExtra },
		BlinkCmpLabelDescription                   { PmenuExtra },
		BlinkCmpKind                               { fg = nge.dummyplug},
		BlinkCmpKindText                           { bg = nge.s2engine, fg = nge.dummyplug, },
		BlinkCmpKindKeyword                        { BlinkCmpKindText },
		BlinkCmpKindMethod                         { BlinkCmpKindText },
		BlinkCmpKindFunction                       { BlinkCmpKindText },
		BlinkCmpKindConstructor                    { BlinkCmpKindText },
		BlinkCmpKindField                          { BlinkCmpKindText },
		BlinkCmpKindVariable                       { BlinkCmpKindText },
		BlinkCmpKindClass                          { BlinkCmpKindText },
		BlinkCmpKindInterface                      { BlinkCmpKindText },
		BlinkCmpKindModule                         { BlinkCmpKindText },
		BlinkCmpKindProperty                       { BlinkCmpKindText },
		BlinkCmpKindUnit                           { BlinkCmpKindText },
		BlinkCmpKindValue                          { BlinkCmpKindText },
		BlinkCmpKindEnum                           { BlinkCmpKindText },
		BlinkCmpKindSnippet                        { BlinkCmpKindText },
		BlinkCmpKindColor                          { BlinkCmpKindText },
		BlinkCmpKindFile                           { BlinkCmpKindText },
		BlinkCmpKindReference                      { BlinkCmpKindText },
		BlinkCmpKindFolder                         { BlinkCmpKindText },
		BlinkCmpKindEnumMember                     { BlinkCmpKindText },
		BlinkCmpKindConstant                       { BlinkCmpKindText },
		BlinkCmpKindStruct                         { BlinkCmpKindText },
		BlinkCmpKindEvent                          { BlinkCmpKindText },
		BlinkCmpKindOperator                       { BlinkCmpKindText },
		BlinkCmpKindTypeParameter                  { BlinkCmpKindText },
		BlinkCmpSource                             { PmenuExtra },
		BlinkCmpGhostText                          { NonText },
		BlinkCmpDoc                                { bg = nge.melchior, fg = nge.penpen },
		BlinkCmpDocBorder                          { bg = nge.melchior, fg = nge.lcl},
		BlinkCmpDocSeparator                       { bg = nge.melchior, fg = nge.lcl },
		BlinkCmpDocCursorLine                      { Visual },
		BlinkCmpSignatureHelp                      { fg = nge.penpen },
		BlinkCmpSignatureHelpBorder                { NormalFloat },
		BlinkCmpSignatureHelpActiveParameter       { LspSignatureActiveParameter },
    TroubleNormal                              { fg = nge.rei, bg = nge.na,},
    TroublePos                                 { fg = nge.rei, bg = nge.na,},
    TroubleNormalNC                            { fg = nge.rei, bg = nge.na,},
    TroublePreview                             { fg = nge.rei, bg = nge.na,},
    TroubleIndentWs                            { fg = nge.rei, bg = nge.na,},
    TroubleIndentLast                          { fg = nge.atfield, bg = nge.na,},
    TroubleIndentMiddle                        { fg = nge.atfield, bg = nge.na,},
    TroubleIndentTop                           { fg = nge.atfield, bg = nge.na,},
    TroubleIconOperator                        { fg = nge.atfield, bg = nge.na,},
    TroubleIndentFoldOpen                      { fg = nge.atfield, bg = nge.na,},
    TroubleIndentFoldClosed                    { fg = nge.atfield, bg = nge.na,},
    TroubleFsBasename                          { fg = nge.rei, bg = nge.na,},
    TroubleFsSource                            { fg = nge.rei, bg = nge.na,},
    TroubleFsFilename                          { fg = nge.rei, bg = nge.na,},
    TroubleFsCount                             { fg = nge.rei, bg = nge.na,},
    TroubleIconNamespace                       { bg = nge.na,},
    TroubleIconFunction                        { bg = nge.na,},
    TroubleIconConstructor                     { bg = nge.na,},
    TroubleIconConstant                        { bg = nge.na,},
    TroubleIconNull                            { bg = nge.na,},
    TroubleIconClass                           { bg = nge.na,},
    TroubleIconNumber                          { bg = nge.na,},
    TroubleIconBoolean                         { bg = nge.na,},
    TroubleIconObject                          { bg = nge.na,},
    TroubleIconArray                           { bg = nge.na,},
  }
end)
---@diagnostic disable
return theme
